### ISSUE TITLE
Mediaelch not updating to latest version 2.10.4

### ISSUE THREAD

**Issue by yuuzhan** [ElGranLoky/mediaelch#2]
If I go into the docker image, the apt update seems to pull the latest version (install doesnt work, but i guess that is part of the docker thing).  But if I remove the image, and re-download the image it doesnt seem to pull the latest version to install.

docker-compose:

```
    mediaelch:
        image: elgranloky/mediaelch:latest
        container_name: mediaelch
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Toronto
            - TAKE_CONFIG_OWNERSHIP=1
            - CLEAN_TMP_DIR=1
            - SECURE_CONNECTION=0
            - VNC_PASSWORD=*****
            - LANG=en_CA.UTF-8
            - LC_ALL=C
            - LANGUAGE=en_CA:en
        volumes:
            - /dockerConfigs/mediaelch:/config
            - /media/movies:/storage/media/movies
            - /media/tv:/storage/media/tv
        ports:
            - 5800:5800
            - 5900:5900
        logging:
            options:
                max-file: "5"
                max-size: "10m"
        restart: unless-stopped
```

```
root@9fa7c97ac396:/tmp# apt-get -y --no-install-recommends install mediaelch
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  mediaelch
1 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
Need to get 2683 kB of archives.
After this operation, 152 kB of additional disk space will be used.
Get:1 https://ppa.launchpadcontent.net/mediaelch/mediaelch-stable/ubuntu jammy/main amd64 mediaelch amd64 2.10.4.0-1~jammy [2683 kB]
Fetched 2683 kB in 5s (488 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
dpkg: unrecoverable fatal error, aborting:
 unknown system group 'messagebus' in statoverride file; the system group got removed
before the override, which is most probably a packaging bug, to recover you
can remove the override manually with dpkg-statoverride
W: No sandbox user '_apt' on the system, can not drop privileges
E: Sub-process /usr/bin/dpkg returned an error code (2)
```
